### ISSUE TITLE
Public directory not created

### ISSUE THREAD

**Issue by RLovelett** [klakegg/docker-hugo#22]
When I run `hugo -D` in these containers the `public` directory never is created (same for `ubuntu` and `ubuntu-onbuild`).

What am I not understanding?

```bash
$ docker run --rm -it -v $PWD:/source --entrypoint /bin/bash klakegg/hugo:ubuntu-onbuild
$ cd /source
$ hugo -D
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.


                   | EN  
-------------------+-----
  Pages            | 26  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 19  
  Processed images |  0  
  Aliases          | 12  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 25 ms
$ ls -alh public
ls: cannot access 'public': No such file or directory
```

**Comment by philwinder** [comment]
@RLovelett This caught me out too. It is due to some opinions in the confusingly named `hugo` wrapper and the addition of the `HUGO_DESTINATION` environmental variable in the dockerfiles. It writes files to `/target` by default.

A quick workaround/fix is to use `hugo-official` for all commands. Then everything works as expected. See the docs here: https://github.com/klakegg/docker-hugo/blob/master/README.md#overriding-entrypoint

**Comment by RLovelett** [comment]
Excellent. Thank you. Great project.
