### ISSUE TITLE
Issues with pandoc vs pandoc-default?

### ISSUE THREAD

**Issue by brianhou** [klakegg/docker-hugo#43]
Thanks for this great set of Docker images!

I've been having some issues getting this work correctly with pandoc. (Pandoc is specified in the front matter with `markup: pandoc`, and I only need the default mathjax flag.)

```shell
$ docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:0.81.0-ext-pandoc server
Start building sites …
pandoc not found in $PATH: Please install.
                  Leaving pandoc content unrendered.
```

It seems that this is an issue with [`pandoc-default`](https://github.com/klakegg/docker-hugo/blob/master/src/files/_script/pandoc.sh#L21) vs `pandoc`. Hugo is [looking directly for `pandoc`](https://github.com/gohugoio/hugo/blob/master/markup/pandoc/convert.go#L55), and the [`pandoc` alias](https://github.com/klakegg/docker-hugo/blob/474b37a210085bacc31676e5e466cb1b3a97e892/src/files/debian/etc/profile.d/hugo.sh#L6) doesn't seem to work because it isn't on the `PATH` for Hugo to pick up.

For now, I've been able to solve the problem by adding a symlink from `pandoc-default` to `pandoc`. Here's the relevant snippet of my working GitLab configuration (which uses 0.77.0, but had the same issue):
```yaml
image: klakegg/hugo:0.77.0-ext-pandoc-ci

pages:
  stage: deploy
  script:
    - ln -s /bin/pandoc-default /bin/pandoc
    - hugo -D
```

Am I using this correctly? Thank you for any suggestions you might have!

**Comment by klakegg** [comment]
Thank you for making me aware of this issue.

Your description of the problem is correct, my solution using an alias does not work when Hugo explicitly inspects `PATH` to find Pandoc. Your workaround clearly does the trick, however I prefer a more permanent solution. :smile:

I've reimplemented support for Pandoc by using a script to still support `HUGO_PANDOC` for customization. The new solution may be tested using `edge` images, for you I've made available `klakegg/hugo:egde-ext-pandoc` and `klakegg/hugo:egde-ext-pandoc-ci` to test my updated solution while still using the variants you are used to.

My tests indicate the new solution works as expected, could you please verify in your environment?

**Comment by brianhou** [comment]
Confirming that both edge images work for me, thank you very much for the fast response!

**Comment by klakegg** [comment]
Updated images bundling Hugo 0.82.0 are building right now, meaning I've removed pushing of the extra images added as part of this issue, and I plan to delete the tags on Docker Hub a bit later (around next Hugo release unless it is too quick). Please make sure to update your build configuration in time, and thank you again for your help. :smile:
